<?php

namespace AppBundle\Repository;

/**
 * FbEndpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbEndpointRepository extends \Doctrine\ORM\EntityRepository
{
}
