<?php

namespace AppBundle\Repository;

/**
 * FbPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbPageRepository extends \Doctrine\ORM\EntityRepository
{
}
