<?php

namespace AppBundle\Repository;

/**
 * FbPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FbQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
