app_fb_page:
    resource: "@AppBundle/Controller/FbPageController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_fb_endpoint:
    resource: "@AppBundle/Controller/FbEndpointController.php"
    type:     annotation

app_fb_post:
    resource: "@AppBundle/Controller/FbPostController.php"
    type:     annotation

facebook:
    resource: "@FacebookBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /social/login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /social/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /social/login

facebook_login:
    path: /social/login/check-facebook

facebook_connect:
    path: /social/login/facebook

