services:
    app.facebook:
        class: FacebookBundle\Service\FacebookService
        arguments: ['@doctrine.orm.entity_manager', "@security.token_storage", "%facebook_app_id%", "%facebook_app_secret%"]
